language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: Hpz1SFDXqguqrYqRF1/8tohe6ZIoOvXt8vMQGPEdEvctwhXWu1PtMRKZ2GIadMLsO7shZSA0PImszNg5UXKref8erWLttkv4WnMxC7ccIwqEZ9e7eBGIiwy7VGMyz3dvtiYcC0DXWJnF5r+/7uA4/c3jgd0GwPr6KlEapm05kx7J6Ixt0iycobmbaRoMVfS6YTutUuM5/F+OFyv9POIxjW6SvexJvHVwbui3LYGZFIVFpv9/0taReMC3hrgspGPlscHP0XQBW0r0LO8ty4lSSQit5yvgZOUp1f17Hni9ZDnxf9At6yxASVeWw0eJjegcXI2SFbc3nCtv9OCueMh7nA39o0jES3bz27slvo9kRno4a4cHytuD9ALowSUszCqWkaP9zGq1CKT6oeQdQa5RNokFcFaglN4S40jVJUMlyQ2/MPnIR/unKASafygZRIE36bNwpxd1AHkep4YHxWKwp3PWKZBnxndaP+793y6ZUOHj8wUdy3kEa/VrgQFXwqiazy83D/vaM0w5/urdbVmRVtN7OQeSPSJqNQ4eAjuwjrIRwVCtpbAAG90YWZkxHaRQvGD7Vrlm/w7rpSIjPeFmsu67bxaUsnHjCsgdiR8d8g4khniGJADGqbqiKaDnb6o4yj+KcF4dzVeV9J8EqdK89tbiMHfFvgr367S4EMWZAYI=
